#!/bin/sh

while read -r line; do
	case $line in
		SOUND*)
			fn_sound="${line#SOUND }"
			;;
		CLOCK*)
			fn_clock="${line#CLOCK }"
			;;
		MEMORY*)
			fn_memory="${line#MEMORY }"
			;;
		STORAGE*)
			fn_storage="${line#STORAGE }"
			;;
		CPU*)
			fn_cpu="${line#CPU }"
			;;
	esac
	xsetroot -name " $fn_sound | $fn_cpu | $fn_storage | $fn_memory | $fn_clock "
done < "$1"

