#!/bin/bash

while true; do
        VOL=$(pactl list sinks | rg '^[[:space:]]Volume:' | awk '{print $5}' | sed 's/%//')
        MUTED=$(pactl list sinks | rg '^[[:space:]]Mute:' | awk '{print $2}')

        if [[ $MUTED == 'yes' ]]; then
		ICON=""
        elif [[ $VOL -ge 50 ]]; then
                ICON=""
        elif [[$VOL -le 0 ]]; then
                ICON=""
        else
                ICON=""
	fi

        echo "SOUND $ICON $VOL% "
        sleep 1;
done
