#!/bin/sh
killall -q lemonbar
$HOME/.config/lemonbar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap          12

bspc config normal_border_color  '#8fbcbb'
bspc config focused_border_color  '#b48ead'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Emacs desktop='^1' follow=on
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a IceCat desktop='^2' follow=on
bspc rule -a discord desktop='^3' follow=on
bspc rule -a Element desktop='^3' follow=on
bspc rule -a Steam desktop='^4' follow=on
bspc rule -a Lutris desktop='^4' follow=on
bspc rule -a Spotify desktop='^5' follow=on
bspc rule -a Gimp desktop='^6' follow=on
