#!/bin/sh
killall -q lemonbar
$HOME/.config/lemonbar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Brave-browser desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a Steam desktop='^4' follow=on
bspc rule -a Lutris desktop='^4' follow=on
bspc rule -a Terraria.bin.x86_64 desktop='^4' state='floating' follow=on
bspc rule -a Spotify desktop='^5' follow=on
