#!/bin/sh
killall -q lemonbar
$HOME/.config/lemonbar/launch.sh -n | lemonbar -f "Roboto Medium"-18 -f "Font Awesome 5 Free Solid"-20 -g 1920x45+0+0 -B"#1d1f21" | $SHELL &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a brave-browser desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a steam desktop='^4' state=floating follow=on
bspc rule -a Spotify desktop='^5' state=floating
